### ISSUE TITLE
Missing abstract class JSONPage?

### ISSUE THREAD

**Issue by beaubbe** [lewiswharf/mailchimp#26]
On the last pull request, in the commit named "Code style + whitespace fixes", the definition of the abstract class JSONPage was removed in content.login.php. I think this part of the code is mandatory because otherwise, the Symphony JSONPage class will be used and will generate an error.

**Comment by nitriques** [comment]
The class is in the core since 2.6.0 https://github.com/symphonycms/symphony-2/blob/1ff58f8c82c5da4900616647c4aa494e651fa6ec/symphony/lib/toolkit/class.jsonpage.php

What about changing [this line](https://github.com/lewiswharf/mailchimp/blob/master/content/content.login.php#L6) for **json**page.php ?

**Comment by beaubbe** [comment]
There is still an error in JSONPage of the core.

**Comment by nitriques** [comment]
Could you test https://github.com/lewiswharf/mailchimp/tree/issue-26 ? Thanks

**Comment by beaubbe** [comment]
It seems to have fixed the problem. Thanks buddy!

**Comment by nitriques** [comment]
No problem guy! You can update to 3.0.1 pal!
